apiVersion : apps/v1
kind: Deployment
metadata:
  name: portal-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: "friendbook.azurecr.io/friendbook"
          ports:
          - containerPort: 3000