apiVersion: v1
kind: Service
metadata:
    name: "friendbook-f307"
    labels:
        app: "friendbook-f307"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "friendbook-f307"